name: Update facade if needed

on:
  push:
    paths:
      - "**.php"

permissions:
  contents: write

jobs:
  update-facade:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Update facade
        run: vendor/bin/testbench autodoc:facades src\Facades

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update facade
